import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      container: {
        center: true,
        padding: {
          default: '1rem',
          sm: '2rem',
          lg: '1rem',
        },
        screens: {
          xs: '100%',
          sm: '576px',
          md: '768px',
          lg: '992px',
          xl: '1200px',
          xxl: '1536px',
          '3xl': '1799px',
          // => @media (min-width: 1440px) { ... }
        },
      },
      backgroundColor: {
        'HeaderBackgroud': '#1F0969',
        'HeaderNav': '#0088C1',
        'buttonBackgroud': '#FFC427',
        'BannerBackgroud': '#140B56',
        'aboutBox': '#FAF9FE',
        'pricingBgColor': '#080D42',  
        'pricingBoxColor': '#F3F3F3',
        
      },
      margin: {
        'marginHeaderList': '50px',
        'xlmarginHeaderList': '25px',
        'lgmarginHeaderList': '18px',
        'trustedHeader': '104px',
        'contentBenefits': '61px',
        'BenefitsIcon': '31px',
        'MbBenefitsBox': '23px',
        'BenefitsMargin': '123px',
        'AboutParagrapheMargin': '100px',
        'aboutBoxMarginLeft': '320px',
        'pricingMargin': '143px',
        'frequentlyHeadingMargin': '52px',
        'frequentlyMargin': '143px',
      },
      padding: {
        'buttonpadding': '14px 25px',
        'headerNav': '500px',
        'xlbuttonpadding': '11px 15px',
        'lgbuttonpadding': '10px 14px',
        'mdbuttonpadding': '10px 12px',
        'Headerpadding': '17px 0',
        'bannerPadding': '183px 0 280px 0',
        'xlbannerPadding': '150px 0 230px 0',
        'lgbannerPadding': '130px 0 180px 0',
        'mdbannerPadding': '100px 0 130px 0',
        'smbannerPadding': '80px 0 100px 0',
        'trustedPadding': '45px 0 42px 0',
        'AssetsPadding': '150px 0 128px 0',
        'benefitsBox': '42px 20px 25px 20px',
        'aboutBoxPadding': '88px 40px 92px 40px',
        'aboutSliderPadding': '35px 40px',
        'tabsPadding': '21px 24px ',
        'tabsPillPadding': '15px 31px',
        'pricingPaddingTop': '117px',
        'pricingBox': '74px 25px 20px 25px',
        'pricingBoxSmall': '29px 44px',
        'plansPading': '35px 0',
        'plansButton': '15px 30px',
        'plansPadding': '172px',
        'frequentlyPadding': '106px',
        'fromBox': '38px 36px',
        'formPaading': '115px',
        'footerPadding': '97px 0 63px 0',
      },
      fontSize: {
        'StrongBanner': '70px',
        'xlStrongBanner': '60px',
        'lgStrongBanner': '49px',
        'mdStrongBanner': '45px',
        'smStrongBanner': '40px',
        'H1Banner': '120px',
        'xlH1Banner': '95px',
        'lgH1Banner': '79px',
        'mdH1Banner': '75px',
        'smH1Banner': '65px',
        'trustedspan': '22px',
        'h3Heading': '44px',
        'benefitsParagraphe': '21px',
        'pricingStrong': '31px',
        'plansH2': '42px',
        'plansFont': '26px',
      },
      colors: {
        'bannerStrongColor': '#FFC427',
        'bannerParagraphe': '#E7E7ED',
        'h2Color': '#080D42',
        'aboutParagraphe': '#00000099',
        'tabsCOlor': '#080D42',
      },
      lineHeight: {
        'h1LineHeight': '90px',
        'xlh1LineHeight': '80px',
        'lgh1LineHeight': '70px',
        'mdh1LineHeight': '60px',
        'smh1LineHeight': '50px',
      },
      height: {
        'starHeight': '19px',
        'xlstarHeight': '18px',
        'lgstarHeight': '17px',
        'mdstarHeight': '16px',
        'smstarHeight': '15px',
        'bannerAfter': '500px',
        'xlbannerAfter': '450px',
        'lgbannerAfter': '400px',
        'mdbannerAfter': '380px',
        'smbannerAfter': '320px',
        'arrowBoxHeight': '50px',
        'aboutBoxHeight': '613px',
        'OrHeight': '32px',
        'planButton': '58px',
      },
      width: {
        'headerLogo': '234px',
        'xlheaderLogo': '190px',
        'lgheaderLogo': '180px',
        'starWidth': '20px',
        'xlstarWidth': '19px',
        'lgstarWidth': '18px',
        'mdstarWidth': '17px',
        'smstarWidth': '16px',
        'bannerAfter': '185px',
        'xlbannerAfter': '165px',
        'lgbannerAfter': '140px',
        'mdbannerAfter': '130px',
        'smbannerAfter': '110px',
        'aboutParagraphe': '920px',
        'arrowBoxWidth': '50px',
        'OrWidth': '32px',
        'planButton': '181px',
      },
      maxWidth: {
        'aboutWidth': '1317px',
        'pricingParagraphe': '1307px',
        'pricingParagrapheBox': '275px',
      },
      minHeight: {
        'pricingParagraphe': '95px',
      },
      borderRadius: {
        'benefitsBox': '20px',
        'aboutBox': '80px',
        'aboutSliderBox': '60px',
        'pricingBox': '50px',
        'plansBox': ' 20px',
        'plansSpan': '20px 20px 0 0',
        'formBox': '30px',
      },
      boxShadow: {
        'trustedShadow': '0px 10px 50px #07070714',
        'benefitsBox': '0px 0px 10px #0000001A',
        'SliderBox': ' 0px 0px 50px #0000001A',
        'fromBox': '0px 0px 26px #0000001A',
      },
      gap: {
        'benefitsGaps': '27px'
      }
    },
  },
  plugins: [],
}
export default config
