/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      container: {
        center: true,
        padding: {
          default: '1rem',
          sm: '2rem',
          lg: '1rem',
        },
      },
      screens: {
        'sm': '640px',
        // => @media (min-width: 640px) { ... }
  
        'md': '768px',
        // => @media (min-width: 768px) { ... }
  
        'lg': '1024px',
        // => @media (min-width: 1024px) { ... }
  
        'xl': '1280px',
        // => @media (min-width: 1280px) { ... }
  
        '2xl': '1536px',
        // => @media (min-width: 1536px) { ... }
        '3xl': '1680px',
        // => @media (min-width: 1699px) { ... }
        '4xl': '1780px',
        // => @media (min-width: 1536px) { ... }
      },
      backgroundColor: {
        'HeaderBackgroud': '#1F0969',
        'HeaderNav': '#0088C1',
        'buttonBackgroud': '#FFC427',
        'BannerBackgroud': '#140B56',
        'aboutBox': '#FAF9FE',
        'pricingBgColor': '#080D42',  
        'pricingBoxColor': '#F3F3F3',
        
      },
      margin: {
        'marginHeaderList': '50px',
        'xlmarginHeaderList': '25px',
        'lgmarginHeaderList': '18px',
        'trustedHeader': '104px',
        '3xltrustedHeader': '85px',
        '2xltrustedHeader': '75px',
        'xltrustedHeader': '70px',
        'lgtrustedHeader': '40px',
        'contentBenefits': '61px',
        '3xlcontentBenefits': '55px',
        '2xlcontentBenefits': '50px',
        'xlcontentBenefits': '45px',
        'lgcontentBenefits': '40px',
        'mdcontentBenefits': '30px',
        'smcontentBenefits': '25px',
        'BenefitsIcon': '31px',
        'MbBenefitsBox': '23px',
        'BenefitsMargin': '123px',
        '3xlBenefitsMargin': '110px',
        '2xlBenefitsMargin': '100px',
        'xlBenefitsMargin': '90px',
        'lgBenefitsMargin': '80px',
        'mdBenefitsMargin': '60px',
        'smBenefitsMargin': '50px',
        'AboutParagrapheMargin': '100px',
        '3xlAboutParagrapheMargin': '90px',
        '2xlAboutParagrapheMargin': '95px',
        'xlAboutParagrapheMargin': '65px',
        'lgAboutParagrapheMargin': '55px',
        'mdAboutParagrapheMargin': '45px',
        'smAboutParagrapheMargin': '40px',
        'aboutBoxMarginLeft': '380px',
        'pricingMargin': '143px',
        '3xlpricingMargin': '120px',
        '2xlpricingMargin': '100px',
        'xlpricingMargin': '90px',
        'lgpricingMargin': '80px',
        'mdpricingMargin': '60px',
        'smpricingMargin': '60px',
        'frequentlyHeadingMargin': '52px',
        '3xlfrequentlyHeadingMargin': '45px',
        '2xlfrequentlyHeadingMargin': '40px',
        'xlfrequentlyHeadingMargin': '35px',
        'lgfrequentlyHeadingMargin': '30px',
        'mdfrequentlyHeadingMargin': '25px',
        'smfrequentlyHeadingMargin': '20px',
        'frequentlyMargin': '143px',
        '3xlfrequentlyMargin': '120px',
        '2xlfrequentlyMargin': '100px',
        'xlfrequentlyMargin': '80px',
        'lgfrequentlyMargin': '70px',
        'mdfrequentlyMargin': '60px',
        'smfrequentlyMargin': '50px',
      },
      padding: {
        'buttonpadding': '14px 25px',
        'headerNav': '500px',
        'xlbuttonpadding': '11px 15px',
        'lgbuttonpadding': '10px 14px',
        'mdbuttonpadding': '10px 12px',
        'Headerpadding': '17px 0',
        'bannerPadding': '183px 0 280px 0',
        'xlbannerPadding': '150px 0 230px 0',
        'lgbannerPadding': '130px 0 180px 0',
        'mdbannerPadding': '100px 0 130px 0',
        'smbannerPadding': '80px 0 100px 0',
        'trustedPadding': '45px 0 42px 0',
        '3xltrustedPadding': '40px 0',
        '2xltrustedPadding': '38px 0',
        'xltrustedPadding': '36px 0',
        'lgtrustedPadding': '35px 0',
        'mdtrustedPadding': '34px 0',
        'mdtrustedPadding': '34px 0',
        'smtrustedPadding': '30px 0',
        'AssetsPadding': '150px 0 128px 0',
        '3xlAssetsPadding': '140px 0 110px 0',
        '2xlAssetsPadding': '120px 0 105px 0',
        'xlAssetsPadding': '100px 0',
        'lgAssetsPadding': '90px 0',
        'mdAssetsPadding': '80px 0',
        'smAssetsPadding': '60px 0',
        'benefitsBox': '42px 20px 25px 20px',
        '3xlbenefitsBox': '40px 20px 22px 20px',
        '2xlbenefitsBox': '35px 18px 20px 18px',
        'xlbenefitsBox': '32px 18px 20px 18px',
        'lgbenefitsBox': '30px 18px 20px 18px',
        'mdbenefitsBox': '25px 17px 18px 17px',
        'smbenefitsBox': '20px 15px 16px 15px',
        'aboutBoxPadding': '88px 40px 92px 40px',
        '3xlaboutBoxPadding': '85px 38px 85px 38px',
        '2xlaboutBoxPadding': '80px 35px',
        'xlaboutBoxPadding': '65px 30px',
        'lgaboutBoxPadding': '50px 30px',
        'mdaboutBoxPadding': '35px 30px',
        'smaboutBoxPadding': '30px',
        'aboutSliderPadding': '35px 40px',
        '3xlaboutSliderPadding': '32px 38px',
        '2xlaboutSliderPadding': '30px 35px',
        'xlaboutSliderPadding': '28px 20px',
        'lggaboutSliderPadding': '25px 18px',
        'mdgaboutSliderPadding': '22px 16px',
        'smgaboutSliderPadding': '20px 15px',
        'tabsPadding': '21px 24px ',
        '2xltabsPadding': '20px 22px ',
        'xltabsPadding': '20px 22px ',
        'lgtabsPadding': '18px 20px ',
        'mdtabsPadding': '15px 30px ',
        'smtabsPadding': '15px 60px ',
        'tabsPillPadding': '15px 31px',
        '2xltabsPillPadding': '15px 30px',
        'xltabsPillPadding': '11px 25px',
        'lgtabsPillPadding': '10px 22px',
        'mdtabsPillPadding': '9px 20px',
        'smtabsPillPadding': '8px 17px',
        'pricingPaddingTop': '117px',
        '3xlpricingPaddingTop': '105px',
        '2xlpricingPaddingTop': '95px',
        'xlpricingPaddingTop': '80px',
        'lgpricingPaddingTop': '70px',
        'mdpricingPaddingTop': '60px',
        'smpricingPaddingTop': '50px',
        'pricingBox': '74px 25px 20px 25px',
        '3xlpricingBox': '70px 25px 20px 25px',
        '2xlpricingBox': '65px 22px 20px 22px',
        'xlpricingBox': '50px 20px 20px 20px',
        'lgpricingBox': '45px 18px 18px 18px',
        'mdpricingBox': '40px 17px 17px 17px',
        'smpricingBox': '30px 15px 15px 15px',
        'pricingBoxSmall': '29px 44px',
        'plansPading': '35px 0',
        'plansButton': '15px 30px',
        'plansPadding': '172px',
        '3xlplansPadding': '150px',
        '2xlplansPadding': '120px',
        'xlplansPadding': '100px',
        'lgplansPadding': '90px',
        'mdplansPadding': '70px',
        'smplansPadding': '50px',
        'frequentlyPadding': '106px',
        '3xlfrequentlyPadding': '100px',
        '2xlfrequentlyPadding': '90px',
        'xlfrequentlyPadding': '80px',
        'lgfrequentlyPadding': '70px',
        'mdfrequentlyPadding': '60px',
        'smfrequentlyPadding': '50px',
        'fromBox': '38px 36px',
        '3xlfromBox': '36px 36px',
        '2xlfromBox': '35px',
        'xlfromBox': '30px',
        'lgfromBox': '28px',
        'mdfromBox': '25px',
        'smfromBox': '20px',
        'formPaading': '115px',
        '3xlformPaading': '100px',
        '2xlformPaading': '90px',
        'xlformPaading': '80px',
        'lgformPaading': '40px',
        'mdformPaading': '35px',
        'smformPaading': '30px',
        'footerPadding': '97px 0 63px 0',
        '3xlfooterPadding': '90px 0 60px 0',
        '2xlfooterPadding': '80px 0 55px 0',
        'xlfooterPadding': '70px 0 50px 0',
        'lgfooterPadding': '60px 0 50px 0',
        'mdfooterPadding': '50px 0',
        'smfooterPadding': '45px 0',
      },
      fontSize: {
        'StrongBanner': '70px',
        'xlStrongBanner': '60px',
        'lgStrongBanner': '49px',
        'mdStrongBanner': '45px',
        'smStrongBanner': '40px',
        'H1Banner': '120px',
        'xlH1Banner': '95px',
        'lgH1Banner': '79px',
        'mdH1Banner': '75px',
        'smH1Banner': '65px',
        'trustedspan': '22px',
        'h3Heading': '44px',
        '3xlh3Heading': '42px',
        '2xlh3Heading': '40px',
        'xlh3Heading': '38px',
        'lgh3Heading': '35px',
        'mdh3Heading': '30px',
        'smh3Heading': '27px',
        '3xlbenefits': '22px',
        'benefitsParagraphe': '21px',
        'pricingStrong': '31px',
        '3xlpricingStrong': '28px',
        '2xlpricingStrong': '27px',
        'xlpricingStrong': '25px',
        'lgpricingStrong': '24px',
        'mdpricingStrong': '22px',
        'smpricingStrong': '20px',
        'plansH2': '42px',
        '3xlplansH2': '40px',
        '2xlplansH2': '38px',
        'xlplansH2': '35px',
        'lgplansH2': '32px',
        'mdplansH2': '28px',
        'smplansH2': '25px',
        'plansFont': '26px',
      },
      colors: {
        'bannerStrongColor': '#FFC427',
        'bannerParagraphe': '#E7E7ED',
        'h2Color': '#080D42',
        'aboutParagraphe': '#00000099',
        'tabsCOlor': '#080D42',
      },
      lineHeight: {
        'h1LineHeight': '90px',
        'xlh1LineHeight': '80px',
        'lgh1LineHeight': '70px',
        'mdh1LineHeight': '60px',
        'smh1LineHeight': '50px',
      },
      height: {
        'starHeight': '19px',
        'xlstarHeight': '18px',
        'lgstarHeight': '17px',
        'mdstarHeight': '16px',
        'smstarHeight': '15px',
        'bannerAfter': '500px',
        'xlbannerAfter': '450px',
        'lgbannerAfter': '400px',
        'mdbannerAfter': '380px',
        'smbannerAfter': '320px',
        'arrowBoxHeight': '50px',
        '3xlarrowBoxHeight': '45px',
        '2xlarrowBoxHeight': '40px',
        'xlarrowBoxHeight': '38px',
        'lgarrowBoxHeight': '35px',
        'mdarrowBoxHeight': '32px',
        'smarrowBoxHeight': '30px',
        'aboutBoxHeight': '613px',
        'OrHeight': '32px',
        'planButton': '58px',
      },
      width: {
        'headerLogo': '234px',
        'xlheaderLogo': '190px',
        'lgheaderLogo': '180px',
        'starWidth': '20px',
        'xlstarWidth': '19px',
        'lgstarWidth': '18px',
        'mdstarWidth': '17px',
        'smstarWidth': '16px',
        'bannerAfter': '185px',
        'xlbannerAfter': '165px',
        'lgbannerAfter': '140px',
        'mdbannerAfter': '130px',
        'smbannerAfter': '110px',
        'trustedImg': '201px',
        '3xltrustedImg': '195px',
        '2xltrustedImg': '185px',
        'xltrustedImg': '145px',
        'lgtrustedImg': '115px',
        'mdtrustedImg': '100px',
        'smtrustedImg': '83px',
        'trustedAfter': '175px',
        '3xltrustedAfter': '158px',
        '2xltrustedAfter': '151px',
        'xltrustedAfter': '136px',
        'lgtrustedAfter': '130px',
        'mdtrustedAfter': '164px',
        'smtrustedAfter': '137px',
        'AssetsImg': '667px',
        'benefitsImg': '80px',
        '3xlbenefitsImg': '75px',
        '2xlbenefitsImg': '70px',
        'xlbenefitsImg': '60px',
        'lgbenefitsImg': '50px',
        'mdbenefitsImg': '45px',
        'sliderImg': '106px',
        '3xlsliderImg': '100px',
        '2xlsliderImg': '90px',
        'xlsliderImg': '70px',
        'lgsliderImg': '60px',
        'mdsliderImg': '50px',
        'smsliderImg': '45px',
        'smbenefitsImg': '40px',
        'aboutParagraphe': '920px',
        'arrowBoxWidth': '50px',
        '3xlarrowBoxWidth': '45px',
        '2xlarrowBoxWidth': '40px',
        'xlarrowBoxWidth': '38px',
        'lgarrowBoxWidth': '35px',
        'mdarrowBoxWidth': '32px',
        'smarrowBoxWidth': '30px',
        'OrWidth': '32px',
        'planButton': '181px',
      },
      maxWidth: {
        'aboutWidth': '1450px',
        'pricingParagraphe': '1307px',
        'pricingParagrapheBox': '275px',
      },
      minHeight: {
        'pricingParagraphe': '95px',
      },
      borderRadius: {
        'benefitsBox': '20px',
        'aboutBox': '80px',
        'aboutSliderBox': '60px',
        'pricingBox': '50px',
        'plansBox': ' 20px',
        'plansSpan': '20px 20px 0 0',
        'formBox': '30px',
      },
      boxShadow: {
        'trustedShadow': '0px 10px 50px #07070714',
        'benefitsBox': '0px 0px 10px #0000001A',
        'SliderBox': ' 0px 0px 50px #0000001A',
        'fromBox': '0px 0px 26px #0000001A',
      },
      gap: {
        'benefitsGaps': '27px',
        '3xlbenefitsGaps': '25px',
        '2xlbenefitsGaps': '22px',
        'xlbenefitsGaps': '20px',
        'lgbenefitsGaps': '18px',
        'mdbenefitsGaps': '15px',
        'smbenefitsGaps': '12px',
      }
    },
  },
  plugins: [],
}

